import ChakraWrapper from './components/chakraWrapper/Chakra';
import Footer from './components/footer';
import NavBar from './components/header';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraWrapper>
          <NavBar></NavBar>
          {children}
          <Footer></Footer>
        </ChakraWrapper>
      </body>
    </html>
  )
}
